modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"

[[mods]]
modId="thaumcraft"
version="1.94.0"
displayName="Thaumcraft Legacy Rebuild"
authors="DARKIFOV"
description='''
Strict Forge 1.19.2 source-driven port of Thaumcraft 4.
Stage 149: strict original TC4 research page parity. Completes exact ConfigResearch icon coverage for all 201 original research keys and guards those resources in GitHub/JAR output.
'''

[[dependencies.thaumcraft]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.thaumcraft]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"
