modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"

[[mods]]
modId="thaumcraft"
version="2.04.0"
displayName="Thaumcraft Legacy Rebuild"
authors="DARKIFOV"
description='''
Strict Forge 1.19.2 source-driven parity port of original Thaumcraft 4.
Stage200: golem bell marker NBT parity, tube/jar renderer visual parity, and resource-pack texture metadata hardening.
'''

[[dependencies.thaumcraft]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.thaumcraft]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"
