package com.darkifov.thaumcraft.porting;

import java.util.List;

/**
 * Strict TC4 1.7.10 item registry map extracted from thaumcraft.common.config.ConfigItems.
 * Empty registryName means the field was declared in TC4 and must be resolved from source before runtime registration.
 */
public final class TC4OriginalItemMap {
    private TC4OriginalItemMap() {}

    public record ItemEntry(String field, String registryName, String originalClass) {}

    public static final List<ItemEntry> ITEMS = List.of(
            new ItemEntry("itemWandCasting", "", ""),
            new ItemEntry("itemWandCap", "", ""),
            new ItemEntry("itemWandRod", "", ""),
            new ItemEntry("itemFocusPouch", "", ""),
            new ItemEntry("itemFocusFire", "", ""),
            new ItemEntry("itemFocusFrost", "", ""),
            new ItemEntry("itemFocusShock", "", ""),
            new ItemEntry("itemFocusTrade", "", ""),
            new ItemEntry("itemFocusExcavation", "", ""),
            new ItemEntry("itemFocusHellbat", "", ""),
            new ItemEntry("itemFocusWarding", "", ""),
            new ItemEntry("itemFocusPrimal", "", ""),
            new ItemEntry("itemEssence", "", ""),
            new ItemEntry("itemWispEssence", "", ""),
            new ItemEntry("itemCrystalEssence", "", ""),
            new ItemEntry("itemResource", "", ""),
            new ItemEntry("itemShard", "", ""),
            new ItemEntry("itemNugget", "", ""),
            new ItemEntry("itemNuggetChicken", "", "ItemNuggetEdible"),
            new ItemEntry("itemNuggetBeef", "", "ItemNuggetEdible"),
            new ItemEntry("itemNuggetPork", "", "ItemNuggetEdible"),
            new ItemEntry("itemNuggetFish", "", "ItemNuggetEdible"),
            new ItemEntry("itemTripleMeatTreat", "", ""),
            new ItemEntry("itemPhotoPlate", "", ""),
            new ItemEntry("itemManaBean", "", ""),
            new ItemEntry("itemZombieBrain", "", "ItemZombieBrain"),
            new ItemEntry("itemResearchNotes", "", ""),
            new ItemEntry("itemInkwell", "", ""),
            new ItemEntry("itemThaumonomicon", "", ""),
            new ItemEntry("itemSpawnerEgg", "", ""),
            new ItemEntry("itemFocusPortableHole", "", ""),
            new ItemEntry("itemFocusPech", "", "ItemFocusPech"),
            new ItemEntry("itemThaumometer", "", ""),
            new ItemEntry("itemFlyingCarpet", "", ""),
            new ItemEntry("itemGolemPlacer", "", ""),
            new ItemEntry("itemGolemBell", "", "ItemGolemBell"),
            new ItemEntry("itemGolemDecoration", "", ""),
            new ItemEntry("itemGolemCore", "", ""),
            new ItemEntry("itemGolemUpgrade", "", ""),
            new ItemEntry("itemArcaneDoor", "", ""),
            new ItemEntry("itemJarFilled", "", ""),
            new ItemEntry("itemJarNode", "", ""),
            new ItemEntry("itemKey", "", "ItemKey"),
            new ItemEntry("itemHandMirror", "", "ItemHandMirror"),
            new ItemEntry("itemTrunkSpawner", "", "ItemTrunkSpawner"),
            new ItemEntry("itemResonator", "", ""),
            new ItemEntry("itemBathSalts", "", ""),
            new ItemEntry("itemBucketDeath", "", ""),
            new ItemEntry("itemBucketPure", "", ""),
            new ItemEntry("itemEldritchObject", "", ""),
            new ItemEntry("itemSanitySoap", "", ""),
            new ItemEntry("itemSanityChecker", "", ""),
            new ItemEntry("itemBottleTaint", "", "ItemBottleTaint"),
            new ItemEntry("itemGoggles", "", ""),
            new ItemEntry("itemBootsTraveller", "", ""),
            new ItemEntry("itemHelmetThaumium", "", "ItemThaumiumArmor"),
            new ItemEntry("itemChestThaumium", "", "ItemThaumiumArmor"),
            new ItemEntry("itemBootsThaumium", "", "ItemThaumiumArmor"),
            new ItemEntry("itemLegsThaumium", "", "ItemThaumiumArmor"),
            new ItemEntry("itemShovelThaumium", "", "ItemThaumiumShovel"),
            new ItemEntry("itemShovelElemental", "", ""),
            new ItemEntry("itemPickThaumium", "", ""),
            new ItemEntry("itemPickElemental", "", ""),
            new ItemEntry("itemSwordThaumium", "", "ItemThaumiumSword"),
            new ItemEntry("itemSwordElemental", "", ""),
            new ItemEntry("itemAxeThaumium", "", ""),
            new ItemEntry("itemAxeElemental", "", ""),
            new ItemEntry("itemHoeThaumium", "", ""),
            new ItemEntry("itemHoeElemental", "", ""),
            new ItemEntry("itemHelmetFortress", "", "ItemFortressArmor"),
            new ItemEntry("itemChestFortress", "", "ItemFortressArmor"),
            new ItemEntry("itemBootsFortress", "", ""),
            new ItemEntry("itemLegsFortress", "", "ItemFortressArmor"),
            new ItemEntry("itemHelmetVoid", "", "ItemVoidArmor"),
            new ItemEntry("itemChestVoid", "", "ItemVoidArmor"),
            new ItemEntry("itemBootsVoid", "", "ItemVoidArmor"),
            new ItemEntry("itemLegsVoid", "", "ItemVoidArmor"),
            new ItemEntry("itemShovelVoid", "", "ItemVoidShovel"),
            new ItemEntry("itemPickVoid", "", ""),
            new ItemEntry("itemSwordVoid", "", ""),
            new ItemEntry("itemSwordCrimson", "", ""),
            new ItemEntry("itemAxeVoid", "", ""),
            new ItemEntry("itemHoeVoid", "", ""),
            new ItemEntry("itemHelmetVoidRobe", "", "ItemVoidRobeArmor"),
            new ItemEntry("itemChestVoidRobe", "", "ItemVoidRobeArmor"),
            new ItemEntry("itemLegsVoidRobe", "", "ItemVoidRobeArmor"),
            new ItemEntry("itemHelmetCultistRobe", "", "ItemCultistRobeArmor"),
            new ItemEntry("itemChestCultistRobe", "", "ItemCultistRobeArmor"),
            new ItemEntry("itemLegsCultistRobe", "", "ItemCultistRobeArmor"),
            new ItemEntry("itemBootsCultist", "", ""),
            new ItemEntry("itemHelmetCultistPlate", "", "ItemCultistPlateArmor"),
            new ItemEntry("itemChestCultistPlate", "", "ItemCultistPlateArmor"),
            new ItemEntry("itemLegsCultistPlate", "", "ItemCultistPlateArmor"),
            new ItemEntry("itemHelmetCultistLeaderPlate", "", "ItemCultistLeaderArmor"),
            new ItemEntry("itemChestCultistLeaderPlate", "", "ItemCultistLeaderArmor"),
            new ItemEntry("itemLegsCultistLeaderPlate", "", "ItemCultistLeaderArmor"),
            new ItemEntry("itemLootbag", "", ""),
            new ItemEntry("itemBaubleBlanks", "", ""),
            new ItemEntry("itemAmuletRunic", "", ""),
            new ItemEntry("itemRingRunic", "", ""),
            new ItemEntry("itemGirdleRunic", "", ""),
            new ItemEntry("itemGirdleHover", "", ""),
            new ItemEntry("itemAmuletVis", "", ""),
            new ItemEntry("itemLegsRobe", "", "ItemRobeArmor"),
            new ItemEntry("itemChestRobe", "", "ItemRobeArmor"),
            new ItemEntry("itemBootsRobe", "", "ItemRobeArmor"),
            new ItemEntry("itemHoverHarness", "", ""),
            new ItemEntry("itemBowBone", "", ""),
            new ItemEntry("itemPrimalArrow", "", "ItemPrimalArrow"),
            new ItemEntry("itemCompassStone", "", ""),
            new ItemEntry("itemPrimalCrusher", "", "ItemPrimalCrusher")
    );

    public static int count() {
        return ITEMS.size();
    }
}
