package com.darkifov.thaumcraft.porting;

import java.util.List;

/**
 * Strict TC4 research graph index extracted from ConfigResearch.
 * Stage116 note: full pages/aspects/parents now also exist in
 * com.darkifov.thaumcraft.research.TC4ResearchRuntimeBridge for runtime use.
 */
public final class TC4OriginalResearchMap {
    private TC4OriginalResearchMap() {}

    public record ResearchCategory(String key, String iconTexture, String backgroundTexture) {}
    public record ResearchEntry(String key, String category) {}

    public static final List<ResearchCategory> CATEGORIES = List.of(
            new ResearchCategory("BASICS", "textures/items/thaumonomiconcheat.png", "textures/gui/gui_researchback.png"),
            new ResearchCategory("THAUMATURGY", "textures/misc/r_thaumaturgy.png", "textures/gui/gui_researchback.png"),
            new ResearchCategory("ALCHEMY", "textures/misc/r_crucible.png", "textures/gui/gui_researchback.png"),
            new ResearchCategory("ARTIFICE", "textures/misc/r_artifice.png", "textures/gui/gui_researchback.png"),
            new ResearchCategory("GOLEMANCY", "textures/misc/r_golemancy.png", "textures/gui/gui_researchback.png"),
            new ResearchCategory("ELDRITCH", "textures/misc/r_eldritch.png", "textures/gui/gui_researchbackeldritch.png")
    );

    public static final List<ResearchEntry> RESEARCH = List.of(
            new ResearchEntry("BASICTHAUMATURGY", "THAUMATURGY"),
            new ResearchEntry("FOCUSFIRE", "THAUMATURGY"),
            new ResearchEntry("FOCUSFROST", "THAUMATURGY"),
            new ResearchEntry("FOCUSHELLBAT", "THAUMATURGY"),
            new ResearchEntry("FOCUSEXCAVATION", "THAUMATURGY"),
            new ResearchEntry("FOCUSWARDING", "THAUMATURGY"),
            new ResearchEntry("FOCUSSHOCK", "THAUMATURGY"),
            new ResearchEntry("FOCUSTRADE", "THAUMATURGY"),
            new ResearchEntry("FOCUSPORTABLEHOLE", "THAUMATURGY"),
            new ResearchEntry("FOCUSPOUCH", "THAUMATURGY"),
            new ResearchEntry("CAP_iron", "THAUMATURGY"),
            new ResearchEntry("CAP_gold", "THAUMATURGY"),
            new ResearchEntry("CAP_thaumium", "THAUMATURGY"),
            new ResearchEntry("CAP_copper", "THAUMATURGY"),
            new ResearchEntry("CAP_silver", "THAUMATURGY"),
            new ResearchEntry("ROD_wood", "THAUMATURGY"),
            new ResearchEntry("ROD_greatwood", "THAUMATURGY"),
            new ResearchEntry("ROD_reed", "THAUMATURGY"),
            new ResearchEntry("ROD_blaze", "THAUMATURGY"),
            new ResearchEntry("ROD_obsidian", "THAUMATURGY"),
            new ResearchEntry("ROD_ice", "THAUMATURGY"),
            new ResearchEntry("ROD_quartz", "THAUMATURGY"),
            new ResearchEntry("ROD_bone", "THAUMATURGY"),
            new ResearchEntry("ROD_silverwood", "THAUMATURGY"),
            new ResearchEntry("SCEPTRE", "THAUMATURGY"),
            new ResearchEntry("ROD_greatwood_staff", "THAUMATURGY"),
            new ResearchEntry("ROD_reed_staff", "THAUMATURGY"),
            new ResearchEntry("ROD_blaze_staff", "THAUMATURGY"),
            new ResearchEntry("ROD_obsidian_staff", "THAUMATURGY"),
            new ResearchEntry("ROD_ice_staff", "THAUMATURGY"),
            new ResearchEntry("ROD_quartz_staff", "THAUMATURGY"),
            new ResearchEntry("ROD_bone_staff", "THAUMATURGY"),
            new ResearchEntry("ROD_silverwood_staff", "THAUMATURGY"),
            new ResearchEntry("WANDPED", "THAUMATURGY"),
            new ResearchEntry("VISAMULET", "THAUMATURGY"),
            new ResearchEntry("WANDPEDFOC", "THAUMATURGY"),
            new ResearchEntry("NODESTABILIZER", "THAUMATURGY"),
            new ResearchEntry("NODESTABILIZERADV", "THAUMATURGY"),
            new ResearchEntry("VISPOWER", "THAUMATURGY"),
            new ResearchEntry("VISCHARGERELAY", "THAUMATURGY"),
            new ResearchEntry("FOCALMANIPULATION", "THAUMATURGY"),
            new ResearchEntry("VAMPBAT", "THAUMATURGY"),
            new ResearchEntry("BASICARTIFACE", "ARTIFICE"),
            new ResearchEntry("ARCANESTONE", "ARTIFICE"),
            new ResearchEntry("GRATE", "ARTIFICE"),
            new ResearchEntry("TABLE", "ARTIFICE"),
            new ResearchEntry("ARCTABLE", "ARTIFICE"),
            new ResearchEntry("RESTABLE", "ARTIFICE"),
            new ResearchEntry("THAUMOMETER", "ARTIFICE"),
            new ResearchEntry("PAVETRAVEL", "ARTIFICE"),
            new ResearchEntry("PAVEWARD", "ARTIFICE"),
            new ResearchEntry("GOGGLES", "ARTIFICE"),
            new ResearchEntry("ARCANEEAR", "ARTIFICE"),
            new ResearchEntry("SINSTONE", "ARTIFICE"),
            new ResearchEntry("LEVITATOR", "ARTIFICE"),
            new ResearchEntry("INFERNALFURNACE", "ARTIFICE"),
            new ResearchEntry("BELLOWS", "ARTIFICE"),
            new ResearchEntry("ENCHFABRIC", "ARTIFICE"),
            new ResearchEntry("INFUSION", "ARTIFICE"),
            new ResearchEntry("FLUXSCRUB", "ARTIFICE"),
            new ResearchEntry("RUNICARMOR", "ARTIFICE"),
            new ResearchEntry("RUNICCHARGED", "ARTIFICE"),
            new ResearchEntry("RUNICHEALING", "ARTIFICE"),
            new ResearchEntry("RUNICKINETIC", "ARTIFICE"),
            new ResearchEntry("RUNICEMERGENCY", "ARTIFICE"),
            new ResearchEntry("BANNERS", "ARTIFICE"),
            new ResearchEntry("RUNICAUGMENTATION", "ARTIFICE"),
            new ResearchEntry("BOOTSTRAVELLER", "ARTIFICE"),
            new ResearchEntry("HOVERHARNESS", "ARTIFICE"),
            new ResearchEntry("HOVERGIRDLE", "ARTIFICE"),
            new ResearchEntry("MIRROR", "ARTIFICE"),
            new ResearchEntry("MIRRORHAND", "ARTIFICE"),
            new ResearchEntry("MIRRORESSENTIA", "ARTIFICE"),
            new ResearchEntry("ARCANEBORE", "ARTIFICE"),
            new ResearchEntry("ARCANELAMP", "ARTIFICE"),
            new ResearchEntry("LAMPGROWTH", "ARTIFICE"),
            new ResearchEntry("LAMPFERTILITY", "ARTIFICE"),
            new ResearchEntry("BONEBOW", "ARTIFICE"),
            new ResearchEntry("PRIMALARROW", "ARTIFICE"),
            new ResearchEntry("ELEMENTALAXE", "ARTIFICE"),
            new ResearchEntry("ELEMENTALPICK", "ARTIFICE"),
            new ResearchEntry("ELEMENTALSWORD", "ARTIFICE"),
            new ResearchEntry("ELEMENTALSHOVEL", "ARTIFICE"),
            new ResearchEntry("ELEMENTALHOE", "ARTIFICE"),
            new ResearchEntry("WARDEDARCANA", "ARTIFICE"),
            new ResearchEntry("JARBRAIN", "ARTIFICE"),
            new ResearchEntry("INFUSIONENCHANTMENT", "ARTIFICE"),
            new ResearchEntry("ARMORFORTRESS", "ARTIFICE"),
            new ResearchEntry("HELMGOGGLES", "ARTIFICE"),
            new ResearchEntry("MASKGRINNINGDEVIL", "ARTIFICE"),
            new ResearchEntry("MASKANGRYGHOST", "ARTIFICE"),
            new ResearchEntry("MASKSIPPINGFIEND", "ARTIFICE"),
            new ResearchEntry("PHIAL", "ALCHEMY"),
            new ResearchEntry("CRUCIBLE", "ALCHEMY"),
            new ResearchEntry("NITOR", "ALCHEMY"),
            new ResearchEntry("ALUMENTUM", "ALCHEMY"),
            new ResearchEntry("ALCHEMICALDUPLICATION", "ALCHEMY"),
            new ResearchEntry("ALCHEMICALMANUFACTURE", "ALCHEMY"),
            new ResearchEntry("ENTROPICPROCESSING", "ALCHEMY"),
            new ResearchEntry("LIQUIDDEATH", "ALCHEMY"),
            new ResearchEntry("BOTTLETAINT", "ALCHEMY"),
            new ResearchEntry("THAUMIUM", "ALCHEMY"),
            new ResearchEntry("PUREIRON", "ALCHEMY"),
            new ResearchEntry("PUREGOLD", "ALCHEMY"),
            new ResearchEntry("PURECOPPER", "ALCHEMY"),
            new ResearchEntry("PURETIN", "ALCHEMY"),
            new ResearchEntry("PURESILVER", "ALCHEMY"),
            new ResearchEntry("PURELEAD", "ALCHEMY"),
            new ResearchEntry("TRANSIRON", "ALCHEMY"),
            new ResearchEntry("TRANSGOLD", "ALCHEMY"),
            new ResearchEntry("TRANSCOPPER", "ALCHEMY"),
            new ResearchEntry("TRANSTIN", "ALCHEMY"),
            new ResearchEntry("TRANSSILVER", "ALCHEMY"),
            new ResearchEntry("TRANSLEAD", "ALCHEMY"),
            new ResearchEntry("TALLOW", "ALCHEMY"),
            new ResearchEntry("ETHEREALBLOOM", "ALCHEMY"),
            new ResearchEntry("BATHSALTS", "ALCHEMY"),
            new ResearchEntry("SANESOAP", "ALCHEMY"),
            new ResearchEntry("ARCANESPA", "ALCHEMY"),
            new ResearchEntry("DISTILESSENTIA", "ALCHEMY"),
            new ResearchEntry("JARLABEL", "ALCHEMY"),
            new ResearchEntry("JARVOID", "ALCHEMY"),
            new ResearchEntry("TUBES", "ALCHEMY"),
            new ResearchEntry("TUBEFILTER", "ALCHEMY"),
            new ResearchEntry("ESSENTIACRYSTAL", "ALCHEMY"),
            new ResearchEntry("CENTRIFUGE", "ALCHEMY"),
            new ResearchEntry("THAUMATORIUM", "ALCHEMY"),
            new ResearchEntry("HUNGRYCHEST", "GOLEMANCY"),
            new ResearchEntry("GOLEMFETTER", "GOLEMANCY"),
            new ResearchEntry("TRAVELTRUNK", "GOLEMANCY"),
            new ResearchEntry("GOLEMSTRAW", "GOLEMANCY"),
            new ResearchEntry("GOLEMWOOD", "GOLEMANCY"),
            new ResearchEntry("GOLEMTALLOW", "GOLEMANCY"),
            new ResearchEntry("GOLEMCLAY", "GOLEMANCY"),
            new ResearchEntry("GOLEMFLESH", "GOLEMANCY"),
            new ResearchEntry("GOLEMSTONE", "GOLEMANCY"),
            new ResearchEntry("GOLEMIRON", "GOLEMANCY"),
            new ResearchEntry("GOLEMTHAUMIUM", "GOLEMANCY"),
            new ResearchEntry("GOLEMBELL", "GOLEMANCY"),
            new ResearchEntry("COREGATHER", "GOLEMANCY"),
            new ResearchEntry("COREFILL", "GOLEMANCY"),
            new ResearchEntry("COREEMPTY", "GOLEMANCY"),
            new ResearchEntry("CORESORTING", "GOLEMANCY"),
            new ResearchEntry("COREUSE", "GOLEMANCY"),
            new ResearchEntry("COREHARVEST", "GOLEMANCY"),
            new ResearchEntry("COREFISHING", "GOLEMANCY"),
            new ResearchEntry("CORELUMBER", "GOLEMANCY"),
            new ResearchEntry("COREGUARD", "GOLEMANCY"),
            new ResearchEntry("COREBUTCHER", "GOLEMANCY"),
            new ResearchEntry("CORELIQUID", "GOLEMANCY"),
            new ResearchEntry("COREALCHEMY", "GOLEMANCY"),
            new ResearchEntry("UPGRADEAIR", "GOLEMANCY"),
            new ResearchEntry("UPGRADEEARTH", "GOLEMANCY"),
            new ResearchEntry("UPGRADEFIRE", "GOLEMANCY"),
            new ResearchEntry("UPGRADEWATER", "GOLEMANCY"),
            new ResearchEntry("UPGRADEORDER", "GOLEMANCY"),
            new ResearchEntry("UPGRADEENTROPY", "GOLEMANCY"),
            new ResearchEntry("ADVANCEDGOLEM", "GOLEMANCY"),
            new ResearchEntry("TINYHAT", "GOLEMANCY"),
            new ResearchEntry("TINYGLASSES", "GOLEMANCY"),
            new ResearchEntry("TINYBOWTIE", "GOLEMANCY"),
            new ResearchEntry("TINYFEZ", "GOLEMANCY"),
            new ResearchEntry("TINYDART", "GOLEMANCY"),
            new ResearchEntry("TINYVISOR", "GOLEMANCY"),
            new ResearchEntry("TINYARMOR", "GOLEMANCY"),
            new ResearchEntry("TINYHAMMER", "GOLEMANCY"),
            new ResearchEntry("ASPECTS", "BASICS"),
            new ResearchEntry("PECH", "BASICS"),
            new ResearchEntry("NODES", "BASICS"),
            new ResearchEntry("WARP", "BASICS"),
            new ResearchEntry("RESEARCH", "BASICS"),
            new ResearchEntry("KNOWFRAG", "BASICS"),
            new ResearchEntry("THAUMONOMICON", "BASICS"),
            new ResearchEntry("ORE", "BASICS"),
            new ResearchEntry("PLANTS", "BASICS"),
            new ResearchEntry("ENCHANT", "BASICS"),
            new ResearchEntry("NODETAPPER1", "BASICS"),
            new ResearchEntry("NODEPRESERVE", "BASICS"),
            new ResearchEntry("NODEJAR", "BASICS"),
            new ResearchEntry("NODETAPPER2", "BASICS"),
            new ResearchEntry("RESEARCHER1", "BASICS"),
            new ResearchEntry("DECONSTRUCTOR", "BASICS"),
            new ResearchEntry("RESEARCHER2", "BASICS"),
            new ResearchEntry("RESEARCHDUPE", "BASICS"),
            new ResearchEntry("CRIMSON", "BASICS"),
            new ResearchEntry("ELDRITCHMINOR", "ELDRITCH"),
            new ResearchEntry("ELDRITCHMAJOR", "ELDRITCH"),
            new ResearchEntry("OCULUS", "ELDRITCH"),
            new ResearchEntry("ENTEROUTER", "ELDRITCH"),
            new ResearchEntry("OUTERREV", "ELDRITCH"),
            new ResearchEntry("PRIMPEARL", "ELDRITCH"),
            new ResearchEntry("PRIMNODE", "ELDRITCH"),
            new ResearchEntry("ADVALCHEMYFURNACE", "ELDRITCH"),
            new ResearchEntry("PRIMALCRUSHER", "ELDRITCH"),
            new ResearchEntry("SANITYCHECK", "ELDRITCH"),
            new ResearchEntry("VOIDMETAL", "ELDRITCH"),
            new ResearchEntry("ESSENTIARESERVOIR", "ELDRITCH"),
            new ResearchEntry("CAP_void", "ELDRITCH"),
            new ResearchEntry("ARMORVOIDFORTRESS", "ELDRITCH"),
            new ResearchEntry("FOCUSPRIMAL", "ELDRITCH"),
            new ResearchEntry("ROD_primal_staff", "ELDRITCH")
    );
}
